dist: trusty
sudo: false
language: c
compiler:
    - gcc
os:
    - linux
addons:
    apt:
        packages:
            - rpm
            - libnl-3-200
            - libnl-3-dev
            - libnl-route-3-200
            - libnl-route-3-dev
            - libnuma-dev
# required for rdma-core
            - build-essential
            - debhelper
            - dh-systemd
            - fakeroot
            - gcc
            - git
            - libudev-dev
            - make
            - ninja-build
            - pandoc
            - pkg-config
            - python
            - valgrind
            - sparse
            - wget
            - abi-compliance-checker
            - abi-dumper
# 32 bit support packages
            - gcc-multilib
    ssh_known_hosts:
        - www.openfabrics.org
        - git.kernel.org

env:
    global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
	- secure: "fei95s92tZdo/jLNt2m2Q/+wqWxJOgvhLM8tLz2pcEFMumVs4I/QMracsI/sb8/sc1gBI+y8khmj6odTqXzYdTB1wPE7KMsJUVW8rqMe1hiIg7tI5O6uw2eT5lcEcYwJg+ZhkQPwb29yjfbb34wR/p1MZGorua11vncOQ8KIxu/uKsPUkc2/wV3MXEeMBea4djRNP7c//0LAzTF5Kyxn0FFUmmlMJgY544Zf0JK4j+oikhEM8g1IYx7Aj8qcQ8Vd4Cvh9kudtf4Z1kR+ajvbnY+O4ds7FgtS1osVR3cJnpNo3+P3Mk8bg0XaLdFef4HJkZNKN/iVPAdQ54Jqb74BLa/ggxpTCXBcF/HI90Ot5Em3mXcMm6x792EWI4fa26nioJGRQeEQFKGFw9ym7W2rn6nSmEeskoVYkI58j7hg8E5+j8ADxOHPWkRLMaedYPLX0cNixtDRc+OzR1kyBZD33px5oTBxfS3Hobf07G8PUHvkhb5EpOXhoa1EdL34wt+uruxZzKDsW1Hw+4f9beQQ2y9ZcKQkMQAEfxWfiLBrQOYpNKHqyodVm/rtKycpE7PObW3BtK8FEPXT/9CMJD55fe3XgcVqORIwxhcYFfbicpOVIkNqTRkVm0t6/QWEVYb2dNs3u4DaudtkMQ961WScIwg88LaRfrPgojiG+XAKwVc="

        - PREFIX=$HOME/install
        - PATH=$PREFIX/bin:$PATH
        - CPPFLAGS="-Werror -I$PREFIX/include"
        - LDFLAGS=-L$PREFIX/lib
        - LD_LIBRARY_PATH=$PREFIX/lib
        - LIBFABRIC_CONFIGURE_ARGS="--prefix=$PREFIX"

# Brew update GNU Autotools so that autogen can succeed
before_install:

    - echo -n | openssl s_client -connect https://scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-


install:
    - ./autogen.sh
    # Build rdma-core because ubuntu trusty doesn't have a sufficiently new version of ibverbs/rdma-core
    # Build verbs only in linux as OS X doesn't have verbs support
    -   git clone --depth 1 -b v13 https://github.com/linux-rdma/rdma-core.git && cd rdma-core && bash build.sh && cd - ;
    -   RDMA_CORE_PATH=$PWD/rdma-core/build ;
    -   export LD_LIBRARY_PATH="$RDMA_CORE_PATH/lib:$LD_LIBRARY_PATH" ;
    -   UCX_BRANCH=v1.2.x;
    -   git clone --depth 1 -b $UCX_BRANCH https://github.com/openucx/ucx.git && cd ucx && ./autogen.sh && ./configure --prefix=$HOME/mlx CFLAGS="-w" && make -j2 install && cd -;
    # Test regular build
#    - ./configure $LIBFABRIC_CONFIGURE_ARGS
#    - make -j2
#    - make install
#    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then make rpm; fi

addons:
  coverity_scan:
    project:
      name: "ofiwg/libfabric"
      description: "Open Fabrics Interfaces"
    notification_email: sean.hefty@intel.com
    build_command_prepend: "./autogen.sh && ./configure"
    build_command: "make -j2"
    branch_pattern: coverity_scan
