name: 'Cornelis'

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  prechecks:
    name: Prechecks
    if: ${{ github.repository == 'cornelisnetworks/libfabric-internal' }}
    uses: cornelisnetworks/libfabric-devel/.github/workflows/ci-prechecks.yml@master
  opa100:
    name: OPA100
    needs: [prechecks]
    if: ${{ github.repository == 'cornelisnetworks/libfabric-internal' }}
    uses: cornelisnetworks/libfabric-devel/.github/workflows/ci-opa100.yml@master
    secrets:
      OPXR_ELASTICSEARCH_CREDENTIALS: ${{ secrets.OPXR_ELASTICSEARCH_CREDENTIALS }}
  cn5000:
    name: CN5000
    needs: [prechecks]
    if: ${{ github.repository == 'cornelisnetworks/libfabric-internal' }}
    uses: cornelisnetworks/libfabric-devel/.github/workflows/ci-cn5000.yml@master
    secrets:
      OPXR_ELASTICSEARCH_CREDENTIALS: ${{ secrets.OPXR_ELASTICSEARCH_CREDENTIALS }}
  cleanup:
    name: Clean Up
    needs: [opa100, cn5000]
    if: ${{ github.repository == 'cornelisnetworks/libfabric-internal' }}
    uses: cornelisnetworks/libfabric-devel/.github/workflows/ci-cleanup.yml@master
