name: Configure Checks
on: [push, pull_request]
permissions: {}
jobs:
  sanitizers:
    permissions:
      contents: read
      pull-requests: read
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        sanitizer: [asan, lsan, tsan, ubsan]
      fail-fast: false
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential clang
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - name: Test --enable-${{ matrix.sanitizer }}
        run: |
          ./autogen.sh
          ./configure --enable-${{ matrix.sanitizer }} CC=clang
      - name: Upload build logs
        if: failure()
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: ${{ matrix.sanitizer }}-config.log
          path: config.log
